Repository predictionmachine/pm-coding-template, pull requests merged in 2021-06, with the labels that each got.

#13 streamline and update template
  .github/workflows/pm-gh-actions.yml
  .idea/.gitignore
  README.md
  requirements-dev.txt
  requirements.txt
Labels: documentation, enhancement

#14 gitignore output/ folder
  .gitignore
Labels: bug, enhancement

#15 add pre-commit & update the README.md, update pm-gh-action to latest version
  .github/workflows/pm-gh-actions.yml
  .pre-commit-config.yaml
  README.md
Labels: documentation, enhancement

#16 add flake8 to pre-commit config and required mypy version
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: documentation, enhancement

#17 update pre-commit-config to 0.1.4
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: enhancement

#18 Fix `mypy` CI step
  .github/workflows/pm-gh-actions.yml
  pyproject.toml
  setup.cfg
Labels: bug

#19 Update coverage config in workflow file, setup.cfg and update readme for badge
  .github/workflows/pm-gh-actions.yml
  README.md
  setup.cfg
Labels: enhancement
