Repository predictionmachine/pm-coding-template, pull requests merged in 2021-09, with the labels that each got.

#22 Update PR template and little cosmetic in docs
  .github/pull_request_template.md
  docs/coding-standard.md
Labels: documentation, enhancement

#25 Feature: Add McCabe complexity option in flake8 config & update dev requirements
  requirements-dev.txt
  setup.cfg
Labels: enhancement

#26 Remove mccabe dependency from dev requirements
  requirements-dev.txt
Labels: enhancement

#27 fix broken links
  docs/coding-standard.md
Labels: bug

#28 Remove PR template
  .github/pull_request_template.md
Labels: bug, documentation, enhancement
